# Generated by Django 6.0.5 on 2026-08-14 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connectors', '0004_reencrypt_sensitive_fields_with_fernet'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectoroverride',
            name='is_default_llm',
            field=models.BooleanField(default=False, help_text='Check to set this AI as the default.', verbose_name='Default LLM'),
        ),
    ]
