# Generated by Django 6.0.5 on 2026-08-14 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_avatar_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='preferred_llm',
            field=models.CharField(blank=True, help_text="User's preferred LLM connector ID. If empty, the system default is used.", max_length=100, null=True),
        ),
    ]
